Build r-tiledbsoma with C++ 20
TileDB-Inc/tiledbsoma-feedstock pull request #231
Opened 2024-11-20 13:26 UTC by johnkerl

Context: https://github.com/single-cell-data/TileDB-SOMA/issues/3154

2024-11-20 15:28 UTC, jdblischak commented
For some reason the osx-64 build isn't using C++20. The [errors](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=41247&view=logs&j=e0208569-136d-54da-4ec5-14d0e8771cbc&t=25992e30-3e2a-5788-2b3e-e373b0534bf7) are the same as in the nightly build (https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/230#issuecomment-2488876179)

2024-11-20 15:29 UTC, jdblischak requested changes
@johnkerl could you please rebase your PR onto the latest from main to include #228?

2024-11-20 16:07 UTC, jdblischak commented
Ah, looking earlier in the build log, I see we have a nice diagnostic signal. R explicitly tells us it is using C++17 on osx-64. 

```sh
* installing *source* package ‘tiledbsoma’ ...
** using staged installation
** updated src/Makevars for system library via pkg-config
** libs
using C++ compiler: ‘clang version 18.1.8’
using C++17
using SDK: ‘NA’‘NA’‘NA’‘’
```

Bizarrely though, the osx-arm64 build also reports `using C++17`, so unclear why it is able to compile successfully.

2024-11-20 16:15 UTC, johnkerl commented
Commit 3:

```
mamba upgrade -c conda-forge conda-smithy -n base
conda smithy rerender --commit auto
```

2024-11-20 16:19 UTC, jdblischak commented
I think it is going to be tough to build r-tiledbsoma with C++20 without the upstream changes in https://github.com/single-cell-data/TileDB-SOMA/pull/3331 that updated `configure` and `src/Makevars.in`.

If we want to fix the nightly build, I think we'll need to 1) fix the build on the branch [nightly-build](https://github.com/TileDB-Inc/tiledbsoma-feedstock/tree/nightly-build), and then 2) modify [`nightly/update-recipe.sh`](https://github.com/TileDB-Inc/tiledbsoma-feedstock/blob/main/.github/scripts/nightly/update-recipe.sh) to incorporate these changes.

2024-11-20 16:24 UTC, johnkerl commented
@jdblischak I was confused

https://github.com/single-cell-data/TileDB-SOMA/pull/3331 is merged to `main` of TileDB-SOMA & I was confusing this PR with the centralized-nightlies which should be testing the day's `main`.

Let me take a look at `nightly-build` and `nightly/update-recipe.sh` which, embarrassingly, I'm not at all familiar with ...

2024-11-20 16:44 UTC, jdblischak commented
> I was confusing this PR with the centralized-nightlies which should be testing the day's `main`.

Good news! The TileDB-SOMA-R build in centralized-tiledb-nightlies is [using C++20](https://github.com/TileDB-Inc/centralized-tiledb-nightlies/actions/runs/11936899558/job/33273058715#step:10:14) and building without error. Thus if we can get the nightly feedstock build to also use C++20, it should _just work_.

2025-01-10 20:36 UTC, johnkerl commented
Closed in favor of #246

2025-01-10 20:36 UTC, closed without merging